name: Build
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 8 * * 1"

jobs:
  Build:
    runs-on: 'ubuntu-latest'
    container: 'node:${{ matrix.node-version }}'
    strategy:
      matrix:
        node-version:
          - "20"
          - "18"
          - "16"
          - "14"

    steps:
      - uses: actions/checkout@v4
      - run: yarn

  # Publish:
  #   runs-on: 'ubuntu-latest'
  #   needs: Build
  #   if: startsWith(github.ref, 'v')
    
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: yarn
  #     - run: yarn publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}      

  Documentation:
    if: github.ref == 'refs/heads/master'
    needs: Build
    uses: byjg/byjg.github.io/.github/workflows/add-doc.yaml@master
    with:
      folder: js
      project: ${{ github.event.repository.name }}
    secrets: inherit